# Generated by Django 5.0.3 on 2024-04-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_img', models.ImageField(upload_to='addshop')),
                ('shop_contact', models.CharField(max_length=12)),
                ('shop_address', models.CharField(max_length=200)),
            ],
        ),
    ]
